version: "3.4"

services:
  wiki:
    container_name: lotrtcg_wiki
    build: 
      context: .
      dockerfile: wiki.Dockerfile
    image: lotrtcg_wiki
    expose:
      - "80"
      - "8080"
    restart: always
    ports:
        # target means in the container
      - target: 80
        # published is what's on the host machine
        published: 1450
    volumes:

       - type: bind
         source: ./wiki
         target: /var/www/html
       - type: bind
         source: ./ext_images
         target: /usr/ext_images
    networks:
      wiki_net:
        ipv4_address: 172.29.0.3
    tty: true


  wiki_db:
    container_name: lotrtcg_wiki_db
    build: 
      context: ..
      dockerfile: docker/wiki_db.Dockerfile
    image: lotrtcg_wiki_db
    ports:
        # target means in the container
      - target: 3306
        # published is what's on the host machine
        published: 3308
    restart: always
    volumes:
       - type: bind
         source: ./database
         target: /var/lib/mysql
    networks:
      wiki_net:
        ipv4_address: 172.29.0.2
    environment:
      MYSQL_ROOT_PASSWORD: [root password here]
      MYSQL_DATABASE: wiki_db
      MYSQL_USER: [user here]
      MYSQL_PASSWORD: [user password here]
      

networks:
  wiki_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24